[workspace]
members = [
    "bdf-parser",
    "eg-bdf",
    "eg-bdf-macros",
]

[patch.crates-io]
embedded-graphics = { git = "https://github.com/jamwaffles/embedded-graphics.git", rev = "2a1df0fdf5f7d199122ec1d39fff22a50ee0493c"}